### ISSUE TITLE
touch-action only for touch and not mouse gestures

### ISSUE THREAD

**Issue by valoricDe** [MilllerTime/react-pointable#6] opened 2017-07-09 14:49 UTC
For anyone who is having problems with preventing the default browser dragging (on Chrome in desktop version). I had to use the following styles as well:

```
.trigger * {
  touch-action: none;
  -webkit-user-drag: none;
  user-drag: none;
}
```

**Comment by MilllerTime** [comment] 2017-07-09 16:45
Hey @valorize, I don't think I completely understand the problem here. Can you please expand on what you were trying to accomplish, and what didn't work as expected? Thanks!

**Comment by valoricDe** [comment] 2017-07-09 22:27
I'm using Pointable like following: 
```
<Pointable
        className="trigger"
        touchAction="none" // Using `touch-action: none` to better simulate hover on touch screens
        onPointerMove={ev => {
            if(this.state.active) {
              let x = (ev.pageX - this.state.startX);
              this.setState({
                styles: {
                  transform: "translate3d(" + x + "px, -" + Math.abs(x)/10 + "px, 0) "+
                  "rotate(" + x/50 + "deg)",
                  opacity: Math.pow(1.01, -Math.max(0, Math.abs(x)-250))
                }
              });
            }
          }
        }
        onPointerDown={ev => {
          this.setState({active: true, startX: ev.pageX});
        }}
        onPointerUp={ev => {
          if(Math.abs(this.state.startX - ev.pageX) > minDiff) {
            if(this.state.startX - ev.pageX > 0) { // swipe right
              this.props.store.proceedToPrevious();
            }
            else { // swipe left
              this.props.store.proceedToNext();
            }
          }

          this.setState({
              startX: 0,
              styles: {},
            });
        }}
      >
        <div className="next">
          <img ...>
        </div>
        <div className="current" style={this.state.styles}>
          <img ...>
        </div>
      </Pointable>
```
class next and current are absolutely positioned over each other.
When I drag the current image the onPointerDown is triggered but shortly after (about 300ms) the browser intercepts the onPointerMove and shows a smaller duplicate of the image which is the moved around by the browser. To stop this I had to use `-webkit-user-drag: none;`.

**Comment by MilllerTime** [comment] 2017-07-10 01:56
Ah, I see - thanks for the additional information.

I believe this is expected behavior. `touch-action` is used to control and override default _touch_ behavior. It does not apply to all pointer types, such a mice. I see how this is surprising at first since `touch-action` goes hand-in-hand with pointer events, but as the name implies it deals with touches only. Use `touch-action: none;` or one of the [more specific values](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) only if you want to disable touch gestures like scrolling and zooming (it appears you've done this too).

As such, clicking and dragging an image with a mouse still initiates the default mouse-driven drag and drop interaction. One way to disable this is with `user-drag: none;`, as you found. Another common practice is to call `event.preventDefault()` within your `pointermove` handler once you've detected your own drag interaction. Yet another alternative is to use native HTML5 drag and drop.

This all has to due with the design of the event systems you're using, and the browser's default gestures. The `<Pointable />` component facilitates using those events in React, but does nothing special itself. The issue described is independent of React or this component. This repository does not attempt to be an authoritative source of information about pointer events - there are better resources available to learn about that. I just wanted to make it simple to use them with React.

Does this help clear things up?

Edit: Would it be more clear to title this issue "touch-action not enough"?

**Comment by valoricDe** [comment] 2017-07-10 10:01
Thank you very much. That was indeed a piece of information I did not find at the internet and lightened me up a lot.

**Comment by MilllerTime** [comment] 2017-07-10 18:49
Excellent, glad to hear. I'm going to close this issue, but your new title should help anyone else who happens to search for this.

Also FWIW, the [W3 pointer events spec](https://www.w3.org/TR/pointerevents/) really helped clarify the unique aspects of pointer events for me, like `touch-action` and pointer capture.

**Closed as completed by MilllerTime** 2017-07-10 18:49 UTC
